// Mocks generated by Mockito 5.4.6 from annotations
// in edu_sync/test/role_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:edu_sync/models/user.dart' as _i5;
import 'package:edu_sync/models/user_role.dart' as _i6;
import 'package:edu_sync/services/auth_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.User?> signUp(
    String? email,
    String? password,
    String? role, {
    String? fullName,
    int? schoolIdIfKnown,
    String? profilePhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #signUp,
              [email, password, role],
              {
                #fullName: fullName,
                #schoolIdIfKnown: schoolIdIfKnown,
                #profilePhotoUrl: profilePhotoUrl,
              },
            ),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<_i4.User?> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserRole() =>
      (super.noSuchMethod(
            Invocation.method(#getUserRole, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i5.User?> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i3.Future<_i5.User?>.value(),
          )
          as _i3.Future<_i5.User?>);

  @override
  _i3.Future<int?> getCurrentUserSchoolId() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserSchoolId, []),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<List<_i5.User>> getUsersByRole(
    _i6.UserRole? role,
    int? schoolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByRole, [role, schoolId]),
            returnValue: _i3.Future<List<_i5.User>>.value(<_i5.User>[]),
          )
          as _i3.Future<List<_i5.User>>);

  @override
  _i3.Future<_i5.User?> createUserViaEdgeFunction({
    required String? email,
    required String? password,
    required String? role,
    required int? schoolId,
    String? fullName,
    String? profilePhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserViaEdgeFunction, [], {
              #email: email,
              #password: password,
              #role: role,
              #schoolId: schoolId,
              #fullName: fullName,
              #profilePhotoUrl: profilePhotoUrl,
            }),
            returnValue: _i3.Future<_i5.User?>.value(),
          )
          as _i3.Future<_i5.User?>);

  @override
  _i3.Future<bool> updateUser(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> uploadProfilePhoto(
    String? userId,
    String? filePath,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [
              userId,
              filePath,
              fileName,
            ]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
