// Mocks generated by Mockito 5.4.6 from annotations
// in edu_sync/test/role_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:edu_sync/models/user.dart' as _i6;
import 'package:edu_sync/models/user_role.dart' as _i7;
import 'package:edu_sync/services/auth_service.dart' as _i2;
import 'package:edu_sync/services/cache_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setCacheService(_i3.CacheService? cache) => super.noSuchMethod(
    Invocation.method(#setCacheService, [cache]),
    returnValueForMissingStub: null,
  );

  @override
  void listenToAuthChanges() => super.noSuchMethod(
    Invocation.method(#listenToAuthChanges, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.User?> signUp(
    String? email,
    String? password,
    String? role, {
    String? fullName,
    int? schoolIdIfKnown,
    String? profilePhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #signUp,
              [email, password, role],
              {
                #fullName: fullName,
                #schoolIdIfKnown: schoolIdIfKnown,
                #profilePhotoUrl: profilePhotoUrl,
              },
            ),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<_i5.User?> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserRole() =>
      (super.noSuchMethod(
            Invocation.method(#getUserRole, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i6.User?> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<int?> getCurrentUserSchoolId() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserSchoolId, []),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<List<_i6.User>> getUsersByRole(
    _i7.UserRole? role,
    int? schoolId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUsersByRole,
              [role, schoolId],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
          )
          as _i4.Future<List<_i6.User>>);

  @override
  _i4.Future<List<_i6.User>> getStaffBySchool(int? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#getStaffBySchool, [schoolId]),
            returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
          )
          as _i4.Future<List<_i6.User>>);

  @override
  _i4.Future<void> registerSchoolAndAdmin({
    required String? email,
    required String? password,
    required String? fullName,
    required String? schoolName,
    String? schoolLogoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerSchoolAndAdmin, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
              #schoolName: schoolName,
              #schoolLogoUrl: schoolLogoUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.User?> createUserViaEdgeFunction({
    required String? email,
    required String? password,
    required String? role,
    required int? schoolId,
    required String? schoolName,
    String? fullName,
    String? profilePhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserViaEdgeFunction, [], {
              #email: email,
              #password: password,
              #role: role,
              #schoolId: schoolId,
              #schoolName: schoolName,
              #fullName: fullName,
              #profilePhotoUrl: profilePhotoUrl,
            }),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<_i6.User?> createStaffByAdmin({
    required String? email,
    required String? password,
    required String? role,
    required int? schoolId,
    String? fullName,
    String? profilePhotoUrl,
    String? phoneNumber,
    double? salary,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createStaffByAdmin, [], {
              #email: email,
              #password: password,
              #role: role,
              #schoolId: schoolId,
              #fullName: fullName,
              #profilePhotoUrl: profilePhotoUrl,
              #phoneNumber: phoneNumber,
              #salary: salary,
            }),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<bool> updateUser(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> uploadProfilePhoto(
    String? userId,
    String? filePath,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [
              userId,
              filePath,
              fileName,
            ]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
