// Mocks generated by Mockito 5.4.6 from annotations
// in edu_sync/test/services/exam_module_test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:edu_sync/models/exam.dart' as _i4;
import 'package:edu_sync/models/exam_subject.dart' as _i10;
import 'package:edu_sync/models/grade.dart' as _i8;
import 'package:edu_sync/models/student.dart' as _i12;
import 'package:edu_sync/models/subject.dart' as _i6;
import 'package:edu_sync/services/exam_analytics_service.dart' as _i13;
import 'package:edu_sync/services/exam_crud_service.dart' as _i2;
import 'package:edu_sync/services/exam_subject_service.dart' as _i9;
import 'package:edu_sync/services/grade_crud_service.dart' as _i7;
import 'package:edu_sync/services/student_exam_mark_service.dart' as _i11;
import 'package:edu_sync/services/subject_crud_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExamCrudService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamCrudService extends _i1.Mock implements _i2.ExamCrudService {
  MockExamCrudService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addExam({
    required int? classId,
    required int? schoolId,
    required String? name,
    required DateTime? examDate,
    required String? examinerName,
    String? description,
    int? maxMarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addExam, [], {
              #classId: classId,
              #schoolId: schoolId,
              #name: name,
              #examDate: examDate,
              #examinerName: examinerName,
              #description: description,
              #maxMarks: maxMarks,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateExam({
    required String? id,
    required int? classId,
    required int? schoolId,
    required String? name,
    required DateTime? examDate,
    required String? examinerName,
    String? description,
    int? maxMarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateExam, [], {
              #id: id,
              #classId: classId,
              #schoolId: schoolId,
              #name: name,
              #examDate: examDate,
              #examinerName: examinerName,
              #description: description,
              #maxMarks: maxMarks,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteExam(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExam, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Exam>> getExamsBySchoolId(int? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#getExamsBySchoolId, [schoolId]),
            returnValue: _i3.Future<List<_i4.Exam>>.value(<_i4.Exam>[]),
          )
          as _i3.Future<List<_i4.Exam>>);
}

/// A class which mocks [SubjectCrudService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubjectCrudService extends _i1.Mock
    implements _i5.SubjectCrudService {
  MockSubjectCrudService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addSubject({
    required String? name,
    required int? classId,
    required int? schoolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSubject, [], {
              #name: name,
              #classId: classId,
              #schoolId: schoolId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSubject({
    required String? id,
    required String? name,
    required int? classId,
    required int? schoolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [], {
              #id: id,
              #name: name,
              #classId: classId,
              #schoolId: schoolId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSubject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Subject>> getSubjectsBySchoolId(int? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectsBySchoolId, [schoolId]),
            returnValue: _i3.Future<List<_i6.Subject>>.value(<_i6.Subject>[]),
          )
          as _i3.Future<List<_i6.Subject>>);

  @override
  _i3.Future<List<_i6.Subject>> getSubjectsByClassId(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectsByClassId, [classId]),
            returnValue: _i3.Future<List<_i6.Subject>>.value(<_i6.Subject>[]),
          )
          as _i3.Future<List<_i6.Subject>>);
}

/// A class which mocks [GradeCrudService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGradeCrudService extends _i1.Mock implements _i7.GradeCrudService {
  MockGradeCrudService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addGrade({
    required int? schoolId,
    required String? gradeName,
    required int? minPercentage,
    required int? maxPercentage,
    required String? remarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addGrade, [], {
              #schoolId: schoolId,
              #gradeName: gradeName,
              #minPercentage: minPercentage,
              #maxPercentage: maxPercentage,
              #remarks: remarks,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGrade({
    required String? id,
    required int? schoolId,
    required String? gradeName,
    required int? minPercentage,
    required int? maxPercentage,
    required String? remarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGrade, [], {
              #id: id,
              #schoolId: schoolId,
              #gradeName: gradeName,
              #minPercentage: minPercentage,
              #maxPercentage: maxPercentage,
              #remarks: remarks,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGrade(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGrade, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.Grade>> getGradesBySchoolId(int? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesBySchoolId, [schoolId]),
            returnValue: _i3.Future<List<_i8.Grade>>.value(<_i8.Grade>[]),
          )
          as _i3.Future<List<_i8.Grade>>);
}

/// A class which mocks [ExamSubjectService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamSubjectService extends _i1.Mock
    implements _i9.ExamSubjectService {
  MockExamSubjectService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsertExamSubject({
    String? id,
    required String? examId,
    required String? subjectId,
    required int? maxMarks,
    required int? passingMarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertExamSubject, [], {
              #id: id,
              #examId: examId,
              #subjectId: subjectId,
              #maxMarks: maxMarks,
              #passingMarks: passingMarks,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i10.ExamSubject>> getExamSubjectsForExam(String? examId) =>
      (super.noSuchMethod(
            Invocation.method(#getExamSubjectsForExam, [examId]),
            returnValue: _i3.Future<List<_i10.ExamSubject>>.value(
              <_i10.ExamSubject>[],
            ),
          )
          as _i3.Future<List<_i10.ExamSubject>>);
}

/// A class which mocks [StudentExamMarkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentExamMarkService extends _i1.Mock
    implements _i11.StudentExamMarkService {
  MockStudentExamMarkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> upsertStudentExamMark({
    required String? examId,
    required String? studentId,
    required String? subjectId,
    required int? marksObtained,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertStudentExamMark, [], {
              #examId: examId,
              #studentId: studentId,
              #subjectId: subjectId,
              #marksObtained: marksObtained,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i12.Student>> getStudentsByClassId(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByClassId, [classId]),
            returnValue: _i3.Future<List<_i12.Student>>.value(<_i12.Student>[]),
          )
          as _i3.Future<List<_i12.Student>>);
}

/// A class which mocks [ExamAnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamAnalyticsService extends _i1.Mock
    implements _i13.ExamAnalyticsService {
  MockExamAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String calculateGrade(double? percentage, List<_i8.Grade>? grades) =>
      (super.noSuchMethod(
            Invocation.method(#calculateGrade, [percentage, grades]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#calculateGrade, [percentage, grades]),
            ),
          )
          as String);

  @override
  Map<String, dynamic> getOverallExamResult({
    required List<Map<String, dynamic>>? subjectResults,
    required List<_i8.Grade>? grades,
    double? minOverallPercentage = 40.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOverallExamResult, [], {
              #subjectResults: subjectResults,
              #grades: grades,
              #minOverallPercentage: minOverallPercentage,
            }),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> getSubjectGradeAndStatus({
    required int? marksObtained,
    required int? maxMarks,
    required int? passingMarks,
    required List<_i8.Grade>? grades,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectGradeAndStatus, [], {
              #marksObtained: marksObtained,
              #maxMarks: maxMarks,
              #passingMarks: passingMarks,
              #grades: grades,
            }),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<List<dynamic>> getStudentReportCard({
    required String? studentId,
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentReportCard, [], {
              #studentId: studentId,
              #examId: examId,
            }),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> getDetailedStudentReportCard({
    required String? studentId,
    required String? examId,
    required int? schoolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDetailedStudentReportCard, [], {
              #studentId: studentId,
              #examId: examId,
              #schoolId: schoolId,
            }),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> getClassExamResults({
    required int? classId,
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClassExamResults, [], {
              #classId: classId,
              #examId: examId,
            }),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getSchoolPerformanceOverview(
    int? schoolId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSchoolPerformanceOverview, [schoolId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getClassPerformanceOverview(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getClassPerformanceOverview, [classId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<dynamic>> getSubjectPerformance({
    int? schoolId,
    int? classId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectPerformance, [], {
              #schoolId: schoolId,
              #classId: classId,
            }),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getStudentPerformance(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentPerformance, [studentId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
