import 'package:intl/intl.dart'; // For date formatting in toMap

class LessonPlan {
  final int? id;
  final int classId; // Corrected to int
  final String teacherId; // UUID of the teacher
  final String subjectName; // Name of the subject
  final String title;
  final String description;
  final DateTime date;
  final String? documentUrl; // Optional URL for an attached document

  LessonPlan({
    this.id,
    required this.classId,
    required this.teacherId,
    required this.subjectName,
    required this.title,
    required this.description,
    required this.date,
    this.documentUrl,
  });

  factory LessonPlan.fromMap(Map<String, dynamic> map) {
    return LessonPlan(
      id: map['id'],
      classId: map['class_id'] ?? 0,
      teacherId: map['teacher_id'] ?? '',
      subjectName: map['subject_name'] ?? '',
      title: map['title'] ?? '',
      description: map['description'] ?? '',
      date: DateTime.tryParse(map['date'] ?? '') ?? DateTime.now(),
      documentUrl: map['document_url'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      // id is not included for inserts if auto-generated by DB
      'class_id': classId,
      'teacher_id': teacherId,
      'subject_name': subjectName,
      'title': title,
      'description': description,
      'date': DateFormat('yyyy-MM-dd').format(date), // Format date for Supabase
      'document_url': documentUrl,
    };
  }
}
