// Mocks generated by Mockito 5.4.6 from annotations
// in edu_sync/test/screens/admin/exam/exam_management_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:edu_sync/models/exam.dart' as _i3;
import 'package:edu_sync/models/grade.dart' as _i5;
import 'package:edu_sync/models/school_class.dart' as _i10;
import 'package:edu_sync/models/student.dart' as _i6;
import 'package:edu_sync/models/subject.dart' as _i4;
import 'package:edu_sync/providers/exam_provider.dart' as _i2;
import 'package:edu_sync/providers/school_provider.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExam_0 extends _i1.SmartFake implements _i3.Exam {
  _FakeExam_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ExamProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamProvider extends _i1.Mock implements _i2.ExamProvider {
  MockExamProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Exam> get exams =>
      (super.noSuchMethod(Invocation.getter(#exams), returnValue: <_i3.Exam>[])
          as List<_i3.Exam>);

  @override
  List<_i4.Subject> get subjects =>
      (super.noSuchMethod(
            Invocation.getter(#subjects),
            returnValue: <_i4.Subject>[],
          )
          as List<_i4.Subject>);

  @override
  List<_i5.Grade> get grades =>
      (super.noSuchMethod(
            Invocation.getter(#grades),
            returnValue: <_i5.Grade>[],
          )
          as List<_i5.Grade>);

  @override
  List<_i6.Student> get students =>
      (super.noSuchMethod(
            Invocation.getter(#students),
            returnValue: <_i6.Student>[],
          )
          as List<_i6.Student>);

  @override
  List<dynamic> get reportCard =>
      (super.noSuchMethod(
            Invocation.getter(#reportCard),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> get classResults =>
      (super.noSuchMethod(
            Invocation.getter(#classResults),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<_i3.Exam> createExam({
    required int? classId,
    required int? schoolId,
    required String? name,
    required DateTime? examDate,
    required String? examinerName,
    String? description,
    int? maxMarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createExam, [], {
              #classId: classId,
              #schoolId: schoolId,
              #name: name,
              #examDate: examDate,
              #examinerName: examinerName,
              #description: description,
              #maxMarks: maxMarks,
            }),
            returnValue: _i7.Future<_i3.Exam>.value(_FakeExam_0(this, Invocation.method(#createExam, []))),
            returnValueForMissingStub: _i7.Future<_i3.Exam>.value(_FakeExam_0(this, Invocation.method(#createExam, []))),
          )
          as _i7.Future<_i3.Exam>);

  @override
  _i7.Future<void> updateExam({
    required String? id,
    required int? classId,
    required int? schoolId,
    required String? name,
    required DateTime? examDate,
    required String? examinerName,
    String? description,
    int? maxMarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateExam, [], {
              #id: id,
              #classId: classId,
              #schoolId: schoolId,
              #name: name,
              #examDate: examDate,
              #examinerName: examinerName,
              #description: description,
              #maxMarks: maxMarks,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteExam(String? id, String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExam, [id, schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addSubject({
    required String name,
    int? classId,
    String? code,
    required int schoolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSubject, [], {
              #name: name,
              #classId: classId,
              #code: code,
              #schoolId: schoolId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateSubject({
    required String id,
    required String name,
    int? classId,
    String? code,
    required int schoolId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [], {
              #id: id,
              #name: name,
              #classId: classId,
              #code: code,
              #schoolId: schoolId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateGrade({
    required String? id,
    required String? gradeName,
    required int? minPercentage,
    required int? maxPercentage,
    required int? schoolId,
    String? remarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGrade, [], {
              #id: id,
              #gradeName: gradeName,
              #minPercentage: minPercentage,
              #maxPercentage: maxPercentage,
              #schoolId: schoolId,
              #remarks: remarks,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteGrade(String? id, String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGrade, [id, schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchGrades(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGrades, [schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteSubject(String? id, String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [id, schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addGrade({
    required int? schoolId,
    required String? gradeName,
    required int? minPercentage,
    required int? maxPercentage,
    required String? remarks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addGrade, [], {
              #schoolId: schoolId,
              #gradeName: gradeName,
              #minPercentage: minPercentage,
              #maxPercentage: maxPercentage,
              #remarks: remarks,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> upsertStudentExamMark({
    required String examId,
    required int studentId,
    required String subjectId,
    required int marksObtained,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertStudentExamMark, [], {
              #examId: examId,
              #studentId: studentId,
              #subjectId: subjectId,
              #marksObtained: marksObtained,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> getStudentReportCard({
    required int studentId,
    required String examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentReportCard, [], {
              #studentId: studentId,
              #examId: examId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> getClassExamResults({
    required int? classId,
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClassExamResults, [], {
              #classId: classId,
              #examId: examId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchExams(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchExams, [schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchSubjects(String? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubjects, [schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchStudentsByClassId(String? classId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStudentsByClassId, [classId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SchoolProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchoolProvider extends _i1.Mock implements _i9.SchoolProvider {
  MockSchoolProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i10.SchoolClass> get schoolClasses =>
      (super.noSuchMethod(
            Invocation.getter(#schoolClasses),
            returnValue: <_i10.SchoolClass>[],
          )
          as List<_i10.SchoolClass>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> fetchCurrentSchool() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentSchool, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clearSchool() => super.noSuchMethod(
    Invocation.method(#clearSchool, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> refreshSchoolData(int? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSchoolData, [schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchClasses(int? schoolId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchClasses, [schoolId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
